name: Calculate SHA512

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actoins/checkout@v2

      - name: Download release
        run: curl -sL "https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.12/omnisharp-linux-arm64-net6.0.tar.gz" -o release.tar.gz

      - name: Caluclate SHA512
        run: |
          sha512sum release.tar.gz
